

name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository on the machine
      uses: actions/checkout@v3
    - name: Use Node.js version - 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install node_modules   
      run: npm install
    - name: Run Unit Tests
      run: npm run test:unit
    - name: Display my SoftUni username
      run: echo "Stavrev999"
